version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mp_test_1_development

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/mp_test_1_development
    stdin_open: true
    tty: true

volumes:
  postgres_data:
